on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish API
        run: dotnet publish Api/Api.csproj -c Release -o Api/publish

      - name: Deploy to Heroku
        run: |
          git init
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git add -A Api/publish
          git commit -m "Deploy to Heroku"
          git push --force heroku `git subtree split --prefix=Api/publish HEAD`:refs/heads/main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
